# Example configs for nodejs project

provider = "openai"
model = "gpt-4o-mini"
check_cmd = "timeout 3s node index.js" # On Macs use gtimeout
api_url = "https://api.openai.com/v1/chat/completions"
api_key = "<OPENAI API KEY>"
max_context = 150000
max_output_tokens = 8096

model = "claude-3-5-haiku-latest"  
check_cmd = "timeout 3s node index.js" # On Macs use gtimeout
api_url = "https://api.anthropic.com/v1/messages"
api_key = "<ANTHROPIC API KEY>"
max_context = 128000
max_output_tokens = 8096

# Deepseek via OpenAI endpoint
provider = "openai"
model = "deepseek-chat"
check_cmd = "timeout 3s node index.js" # On Macs use gtimeout
api_url = "https://api.deepseek.com/v1/chat/completions"
api_key = "<DEEPSEEK API KEY>"
max_context = 100000
max_output_tokens = 8096

